name: Phorcys CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build bandit flake8

      - name: Linting
        run: flake8 src tests

      - name: Static security analysis
        run: bandit -c pyproject.toml -r src

      - name: Build package
        run: python -m build
